version: '2'
services:
    mylocalmarket-app:
        image: mylocalmarket
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mylocalmarket-mysql:3306/mylocalmarket?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=mylocalmarket-elasticsearch:9300
        ports:
            - 8080:8080
    mylocalmarket-mysql:
        extends:
            file: mysql.yml
            service: mylocalmarket-mysql
    mylocalmarket-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mylocalmarket-elasticsearch
